# set schema for titles
# schema for each basic graph title
MODELNAMETITLE = 'SALES BY MODEL NAME'
MODELSERIESTITLE = 'SALES BY MODEL SERIES'
SALESMANTITLE = 'SALES BY SALESMAN'
MONTHTITLE = 'SALES BY MONTH'
QUARTERTITLE = 'SALES BY QUARTER'

# schema for each advanced graph title
MODELNAMEBYMONTHTITLE = 'MONTHLY SALES BY MODEL NAME'
MODELSERIESBYMONTHTITLE = 'MONTHLY SALES BY MODEL SERIES'
SALESMANBYMONTHTITLE = 'MONTHLY SALES BY SALESMAN'
MODELNAMEBYQUARTERTITLE = 'QUARTERLY SALES BY MODEL NAME'
MODELSERIESBYQUARTERTITLE = 'QUARTERLY SALES BY MODEL SERIES'
SALESMANBYQUARTERTITLE = 'QUARTERLY SALES BY SALESMAN'